Mainweb/Mainweb/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from background_ms.views import Index_layoutView
from user.views import SendKeyWordsEmailView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', Index_layoutView.as_view(), name='index_layout'),
    url(r'^backms/', include('background_ms.urls', namespace='backms')),
    url(r'^user/', include('user.urls', namespace='user')),
    # just for test
    # url(r'^test$', TemplateView.as_view(template_name='change_passwd.html')),
    url(r'^test$', SendKeyWordsEmailView.as_view()),
]

urlpatterns += staticfiles_urlpatterns()

Mainweb/apps/background_ms/urls.py
from django.conf.urls import url
from .views import IndexView, Index_layoutView, GraphShowView, CompareView
from .views import DownloadAsExcelView

urlpatterns = [
    url('^index_layout$', Index_layoutView.as_view(), name='index_layout'),
    url('^index/$', IndexView.as_view(), name='index'),
    url('^graph/$', GraphShowView.as_view(), name='graph'),
    url('^compare/$', CompareView.as_view(), name='compare'),
    url('^download_csv/', DownloadAsExcelView.as_view(), name='down_csv')
]

Mainweb/apps/user/urls.py
from django.conf.urls import url
from .views import LoginView, UserView, LogoutView, ChangePasswordView, AddUserView, \
    CreateUserListView, DeleteUserView, ChangeDetiails

urlpatterns = [
    url('^me/$', UserView.as_view(), name='me'),
    url('^login/$', LoginView.as_view(), name='login'),
    url('^logout/$', LogoutView.as_view(), name='logout'),
    url('^change_detils/$', ChangeDetiails.as_view(), name='change_details'),
    url('^change_passwd/$', ChangePasswordView.as_view(), name='change_passwd'),
    url('^add_user/$', AddUserView.as_view(), name='add_user'),
    url('^create_user_list/$', CreateUserListView.as_view(), name='create_user_list'),
    url('^del_user/$', DeleteUserView.as_view(), name='del_user'),
]

Mainweb/templates/change_details.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>

    <meta charset="utf-8">
    <title>修改信息</title>
    <link href="{% static 'css/bootstrap.min14ed.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min93e3.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min862f.css' %}" rel="stylesheet">

</head>

<body class="gray-bg">
<div class="wrapper wrapper-content animated fadeIn">
    <div class="row m-b-lg">
        <div class="col-sm-12">
            <div class="tabs-container">

                <div class="tabs-left">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#tab-8"> 信息修改</a>
                        </li>
                        <li class=""><a data-toggle="tab" href="#tab-9"> 密码修改</a>
                        </li>
                    </ul>
                    <div class="tab-content ">
                        <div id="tab-8" class="tab-pane active">
                            <div class="panel-body">
                                <form action="{% url 'user:change_details' %}" method="post">
                                    <strong style="color: #c9a8ff;padding-bottom: 20px">信息修改</strong>
                                    <div class="form-group">
                                        <label></label>
                                        <p style="color: #14b25b;">{{ msg }}</p>
                                    </div>
                                    <p class="text-info">{{ msg_good }}</p>
                                    <p class="text-danger">{{ msg_bad }}</p>
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input name="email" type="text" value="{{ user.email }}"
                                               placeholder="请输入您的新E-mail"
                                               class="form-control">
                                    </div>
                                    <button class="btn btn-primary " type="submit"><i class="fa fa-check"></i>&nbsp;提交
                                    </button>
                                    {% csrf_token %}
                                </form>
                            </div>
                        </div>
                        <div id="tab-9" class="tab-pane">
                            <div class="panel-body">
                                <strong style="color: #c9a8ff;padding-bottom: 20px">密码修改(提交后返回登陆页面)</strong>
                                <div class="form-group">
                                    <label></label>
                                </div>
                                <div class="col-md-12">
                                    <form action="{% url 'user:change_passwd' %}" method="post">
                                        <div class="form-group">
                                            <label>新密码</label>
                                            <input name="password1" type="password" placeholder="请输入密码"
                                                   class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label>确认密码</label>
                                            <input name="password2" type="password" placeholder="请输入密码"
                                                   class="form-control">
                                        </div>
                                        <button class="btn btn-primary " type="submit"><i class="fa fa-check"></i>&nbsp;提交
                                        </button>
                                        {% csrf_token %}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/content.min.js' %}"></script>
</body>
</html>

Mainweb/templates/graph_flot.html
<!DOCTYPE html>
<html>

{% load staticfiles %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>详情</title>
    <link href="{% static 'css/bootstrap.min14ed.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min93e3.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min862f.css' %}" rel="stylesheet">

</head>

<body class="gray-bg">
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <label class="col-sm-2 control-label" style="text-align: right">选择日期: </label>
            <form action="{% url 'backms:graph' %}" method="get">
                <input type="text" value="{{ time_want }}" class="demo-input" name="time_interval" placeholder="请选择日期"
                       id="test1">
                <input type="hidden" name="title" value="{{ title }}">
                <input type="submit" value="提交">
            </form>
        </div>
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>积极舆论占比</h5>

                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>

                </div>
                <div class="ibox-content">
                    <div class="flot-chart">
                        <div class="flot-chart-content" id="flot-line-chart-multi"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        {% if recommend_words %}
            <div class="col-sm-3">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>推荐添加</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover margin bottom">
                                    <thead>
                                    <tr>
                                        <th class="text-center">关键词</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for word in recommend_words %}
                                        <tr>
                                            <td class="text-center small">{{ word }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        {% if frequency_s %}
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>主题相关词</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover margin bottom">
                                    <thead>
                                    <tr>
                                        <th class="text-center">排名</th>
                                        <th class="text-center">关键词</th>
                                        <th class="text-center">频数</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for title,count in frequency_s %}
                                        <tr>
                                            <td class="text-center">{{ forloop.counter }}</td>
                                            <td class="text-center small">{{ title }}</td>
                                            <td class="text-center"><span class="label label-primary">{{ count }}</span>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        {% if suggests_list %}
            <div class="col-sm-3">
                {# This div is to get suggestions #}
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover margin bottom">
                                    <thead>
                                    <tr>
                                        <th class="text-center">相关建议</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for suggest in suggests_list %}
                                        <tr>
                                            <td class="text-center small">{{ suggest }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="col-sm-3">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>其他操作</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                {% if frequency_s %}
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-12">
                                <form action="{% url 'backms:down_csv' %}" method="get">
                                    <input type="hidden" name="title" value="{{ title }}">
                                    <input type="hidden" name="time_interval" value="{{ time_interval }}">
                                    <button type="submit" class="btn btn-sm btn-info">导出CSV</button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12">
                            <form action="{% url 'backms:index' %}" method="post">
                                <input type="hidden" name="title_del" value="{{ title }}">
                                <button type="submit" class="btn btn-sm btn-danger">删除</button>
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'js/content.min.js' %}"></script>
<script src="{% static 'js/laydate/laydate.js' %}"></script>
<script>
    //年月范围
    laydate.render({
        elem: '#test1'
        , range: true
    });
    $(function () {
        function e(e, o) {
            return "&yen;" + e.toFixed(o.tickDecimals)
        }

        function o(o) {
            $.plot($("#flot-line-chart-multi"), [
                    {data: t, label: "积极舆论"},
                ],
                {
                    xaxes: [{mode: "time"}],
                    yaxes: [{min: 0}, {alignTicksWithAxis: "right" == o ? 1 : null, position: o, tickFormatter: e}],
                    legend: {position: "sw"},
                    {# this colors controls the color of graph #}
                    colors: ["#1ab394"],
                    grid: {
                        color: "#999999",
                        hoverable: !0,
                        clickable: !0,
                        tickColor: "#D4D4D4",
                        borderWidth: 0,
                        hoverable: !0
                    },
                    tooltip: !0,
                    tooltipOpts: {
                        content: "%s %x 为 %y%", xDateFormat: "%y-%0m-%0d", onHover: function () {
                        }
                    }
                });
        }

        var t = [
            {% for time,pos_rate in motion_tup %}
                [{{ time }}000, {{ pos_rate }}],
            {% endfor %}
        ];
        o("right"), $("button").click(function () {
            o($(this).text())
        })
    });

</script>
</body>
</html>

Mainweb/templates/index.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>首页</title>
    <link href="{% static 'css/bootstrap.min14ed.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min93e3.css' %}" rel="stylesheet">
    <!-- Morris -->
    <link href="{% static 'css/plugins/morris/morris-0.4.3.min.css' %}" rel="stylesheet">
    <!-- Gritter -->
    <link href="{% static 'js/plugins/gritter/jquery.gritter.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min862f.css' %}" rel="stylesheet">
</head>
<body class="gray-bg">
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>爬虫爬取关键词</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    {% if user.is_staff %}
                        <div class="row">
                            <form action="{% url 'backms:index' %}" method="post">
                                <div class="col-sm-6">
                                    <p class="text-info">{{ msg_good }}</p>
                                    <p class="text-danger">{{ msg_bad }}</p>
                                    <div class="input-group">
                                        <input name="key_words" required="required" type="text" placeholder="添加主题"
                                               class="input-sm form-control">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-sm btn-primary">添加 </button>
                                        </span>
                                    </div>
                                </div>
                                {% csrf_token %}
                            </form>
                        </div>
                    {% endif %}
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <form action="{% url 'backms:compare' %}" method="get">

                                <thead>
                                <tr>
                                    <th></th>
                                    <th>关键词</th>
                                    <th>添加人</th>
                                    <th>添加日期</th>
                                    <th>
                                        <button type="submit" class="btn btn-sm btn-info">进行对比</button>
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for title in need_title %}
                                    <tr>
                                        <td>
                                            <div class="icheckbox_square-green checked" style="position: relative;">
                                                <input
                                                        type="checkbox" checked="" class="i-checks" name="input[]"
                                                        style="position: absolute; opacity: 0;">
                                                <ins class="iCheck-helper"
                                                     style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;"></ins>
                                            </div>
                                        </td>
                                        <td>
                                            <a href="{% url 'backms:graph' %}?title={{ title.key_words }}"
                                               target="_blank">{{ title.key_words }}</a>
                                        </td>
                                        <td>{{ title.add_user }}</td>
                                        <td>{{ title.create_time }}</td>
                                        <td>
                                            <label class="checkbox-inline">
                                                <input type="checkbox" value="{{ title.key_words }}"
                                                       name="compare_check_box">添加对比</label>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </form>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.spline.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.symbol.js' %}"></script>
<script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>
<script src="{% static 'js/demo/peity-demo.min.js' %}"></script>
<script src="{% static 'js/content.min.js' %}"></script>
<script src="{% static 'js/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'js/plugins/easypiechart/jquery.easypiechart.js' %}"></script>
<script src="{% static 'js/plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'js/demo/sparkline-demo.min.js' %}"></script>
<script src="{% static 'js/plugins/iCheck/icheck.min.js' %}"></script>

</body>
</html>

Mainweb/templates/index_layout.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>首页</title>

    <link rel="shortcut icon" href="favicon.ico">
    <link href="{% static 'css/bootstrap.min14ed.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min93e3.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min862f.css' %}" rel="stylesheet">
</head>

<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
<div id="wrapper">
    <!--左侧导航开始-->
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="nav-close"><i class="fa fa-times-circle"></i>
        </div>
        <div class="sidebar-collapse">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        <span>
                        </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                               <span class="block m-t-xs"><strong class="font-bold">{{ user.username }}</strong></span>
                                    {% if user.is_staff %}
                                        <span class="text-muted text-xs block">管理员<b class="caret"></b></span>
                                    {% else %}
                                        <span class="text-muted text-xs block">普通用户<b class="caret"></b></span>

                                    {% endif %}
                                </span>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="{% url 'user:logout' %}">安全退出</a>
                            </li>
                        </ul>
                    </div>
                    <div class="logo-element">H+
                    </div>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa fa-bar-chart-o"></i>
                        <span class="nav-label">统计信息</span>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        {% if need_title %}
                            {% for title in need_title %}
                                <li>
                                    <a class="J_menuItem"
                                       href="{% url 'backms:graph' %}?title={{ title }}">{{ title }}</a>
                                </li>
                            {% endfor %}
                        {% else %}
                            <li>
                                <a class="J_menuItem">暂无关键词</a>
                            </li>
                        {% endif %}


                    </ul>
                </li>

                <li>
                    <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">个人中心</span><span
                            class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">

                        <li><a class="J_menuItem" href="{% url 'user:me' %}">个人信息</a></li>
                        <li><a class="J_menuItem" href="{% url 'user:change_details' %}">修改信息</a></li>
                        {% if user.is_staff %}
                            <li><a class="J_menuItem" href="{% url 'user:add_user' %}">添加用户</a></li>
                            <li><a class="J_menuItem" href="{% url 'user:create_user_list' %}">修改已有用户</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <!--左侧导航结束-->
    <!--右侧部分开始-->
    <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#">
                        <i class="fa fa-bars"></i> 收/展侧边栏
                    </a>
                </div>
            </nav>
        </div>
        <div class="row content-tabs">
            <button class="roll-nav roll-left J_tabLeft"><i class="fa fa-backward"></i>
            </button>
            <nav class="page-tabs J_menuTabs">
                <div class="page-tabs-content">
                    <a href="javascript:;" class="active J_menuTab" data-id="index_v1.html">首页</a>
                </div>
            </nav>
            <button class="roll-nav roll-right J_tabRight"><i class="fa fa-forward"></i>
            </button>
            <div class="btn-group roll-nav roll-right">
                <button class="dropdown J_tabClose" data-toggle="dropdown">关闭操作<span class="caret"></span>

                </button>
                <ul role="menu" class="dropdown-menu dropdown-menu-right">
                    <li class="J_tabShowActive"><a>定位当前选项卡</a>
                    </li>
                    <li class="divider"></li>
                    <li class="J_tabCloseAll"><a>关闭全部选项卡</a>
                    </li>
                    <li class="J_tabCloseOther"><a>关闭其他选项卡</a>
                    </li>
                </ul>
            </div>
            <a href="{% url 'user:logout' %}" class="roll-nav roll-right J_tabExit"><i class="fa fa fa-sign-out"></i> 退出</a>
        </div>
        <div class="row J_mainContent" id="content-main">
            <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="{% url 'backms:index' %}"
                    frameborder="0" data-id="index_v1.html" seamless></iframe>
        </div>
        <div class="footer">
        </div>
    </div>
    <!--右侧部分结束-->
    <!--右侧边栏开始-->
    <div id="right-sidebar">
        <div class="sidebar-container">

            <ul class="nav nav-tabs navs-3">

            </ul>

        </div>
    </div>
    <!--右侧边栏结束-->
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.min.js' %}"></script>
<script src="{% static 'js/hplus.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/contabs.min.js' %}"></script>
<script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
</body>

</html>